### ISSUE TITLE
Use string.Join

### ISSUE THREAD

**Issue by kassemsandarusi** [say25/BingoBoardChecker#3]
https://github.com/say25/BingoBoardChecker/blob/be2ec8262a24bd8ab163791a6624a76f9738367d/src/BingoChecker/IntListExtensions.cs#L10

https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netframework-4.8#System_String_Join_System_String_System_Collections_Generic_IEnumerable_System_String__

**Comment by say25** [comment]
I think you mean https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netcore-3.1#System_String_Join_System_String_System_Collections_Generic_IEnumerable_System_String

**Comment by say25** [comment]
Done 304f7e75b0a58ef7b11fa374a74f4dc8859d344a
